Tp3_ej5:
	gcc tp3_ej5_server.c -o ej5_server -pthread
	gcc tp3_ej5_cliente.c -o ej5_cliente
all:
	gcc tp3_ej5_server.c -o ej5_server -pthread
	gcc tp3_ej5_cliente.c -o ej5_cliente
clean:
	rm ej5_server
	rm ej5_cliente
