tp3_ej4:
	gcc -o server servidor.c -lrt -lpthread
	gcc -o cliente cliente.c -lrt -lpthread
all:
	gcc -o server servidor.c -lrt -lpthread
	gcc -o cliente cliente.c -lrt -lpthread
clean:
	rm server
	rm cliente
