tp3_ej4:
	gcc -o ej4_server tp3_ej4_servidor.c -lrt -lpthread
	gcc -o ej4_cliente tp3_ej4_cliente.c -lrt -lpthread
all:
	gcc -o ej4_server tp3_ej4_servidor.c -lrt -lpthread
	gcc -o ej4_cliente tp3_ej4_cliente.c -lrt -lpthread

cliente:
	gcc -o ej4_cliente tp3_ej4_cliente.c -lrt -lpthread

servidor:
	gcc -o ej4_server tp3_ej4_servidor.c -lrt -lpthread

clean:
	rm ej4_server
	rm ej4_cliente
